export const Games2023_24 = [
    'Two Point Hospital',
    'Minecraft',
    'Ballistic NG',
    'Papers Please',
    'Stardew Valley',
    'Amnesia: Dark Descent',
    'Project Zomboid',
    'Counter Strike 2',
    'Amnesia: The Bunker',
    'VR: Traffic Jam',
    'VR: Cook Out - A Sandwich Tale',
    'VR: Beat Saber',
    'A Bavarian Tale',
    'Alien Isolation',
    'Graveyard Shift',
    'Layers of Fear',
    'Parkitect',
    'Anno 1800',
    'Dead Space 1, 2',
    'Supermarket Simulator',
    'Sims 4',
    'Plants vs Zombies',
    'Cities Skylines II',
    'Chilla\'s Art: Convenience Store',
    'Battlefield 4',
    'VR: The Lab',
    'VR: Down The Rabbit Hole',
    'Indigo Park (Demo)',
    'Dead Space 3',
    'Euro Truck Simulator 2',
    'The Cursed Tape',
    'Assetto Corsa',
    'Chilla\'s Art: Parasocial',
    'Fears of Fathom: Home Alone',
    'Simulacra',
    'Fortnite',
    'Elden Ring + DLC',
    'Chilla\'s Art: Onryo',
    'Chilla\'s Art: Ghost Train',
    'Chilla\'s Art: Missing Children',
    'Black Myth: Wukong',
    'This bed we made',
    'Outlast + DLC',
    'Outlast 2',
    'Silent Hill 2',
    'Chernobylite'
  ];
  
  export const Games2024_25 = [
    'Dying Light 1 + DLC',
    'Subnautica',
    'Slime Rancher',
  ];

  export const Games2025_26 = [
    'nicht definiert',
    'nicht definiert',
    'nicht definiert',
  ];
  